# Generated by Django 3.1 on 2020-08-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_orderitem_quantify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantify',
            new_name='quantity',
        ),
    ]
